name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '* * 1, 10, 20, 30 * *' # Runs every hour, on the hour
  workflow_dispatch: 
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "erikaduan.github.io/index.xml"
